apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goserver
  name: goserver-deplyment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - image: andrebezerramarinho1/goserver:hash-38de9b4
        name: goserver
        ports:
        - containerPort: 8080
